language: bash

env:
  global:
    - IMAGE_NAME='wicker25/whatstrapp'

addons:
  apt:
    packages:
      - realpath

install:
  - docker-compose -f .travis/docker-compose.yml build

before_script:
  - VERSION=$(grep 'ENV VERSION' ./Dockerfile | awk '{ print $3 }')
  - curl -L 'https://github.com/vishnubob/wait-for-it/blob/master/wait-for-it.sh?raw=true' -o .travis/wait-for-it.sh
  - chmod +x .travis/wait-for-it.sh

script:
  - docker-compose -f .travis/docker-compose.yml up -d
  - .travis/wait-for-it.sh --timeout=120 127.0.0.1:8025
  - .travis/wait-for-it.sh --timeout=120 127.0.0.1:5601

after_script:
  - docker-compose -f .travis/docker-compose.yml stop
  - docker-compose -f .travis/docker-compose.yml rm -f

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/docker-push.sh
  on:
    branch: master
